const state={medialBob:'yes',lateral:'yes',acl:'yes',mcl:'yes',pfj:'no',inflammatory:'no',sex:'female',asa:'2'};
const revision={
 '<55':{male:{tkr:6.04,all:13.49,fixed:9.00,mobile:17.06},female:{tkr:5.24,all:14.25,fixed:10.07,mobile:17.53}},
 '55-64':{male:{tkr:3.81,all:8.93,fixed:6.19,mobile:11.09},female:{tkr:3.46,all:10.44,fixed:7.18,mobile:12.56}},
 '65-74':{male:{tkr:2.55,all:6.43,fixed:4.26,mobile:7.84},female:{tkr:2.35,all:8.07,fixed:4.93,mobile:10.32}},
 '75+':{male:{tkr:1.71,all:4.52,fixed:2.93,mobile:5.75},female:{tkr:1.64,all:6.94,fixed:4.31,mobile:8.69}}
};
const $=id=>document.getElementById(id); const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function ageBand(a){return a<55?'<55':a<65?'55-64':a<75?'65-74':'75+'}
function ukaOks(age,pre){const ad=age<=75?.14*(age-65):.14*10-.18*(age-75);return clamp(37.5+.24*(pre-21.9)+ad,0,48)}
function tkrOks(age,sex,bmi,asa,pre,ffd,acl){let am=age<60?0:age<70?.8:age<80?1.4:-2.5,mi=age<60?0:age<70?4.8:age<80?4.3:8.1;let x=32.9+am-1.5*(bmi/10)+.4*pre+(asa>=3?-2:0)+(ffd>0?1.7:0)+(acl==='no'?1:0);if(sex==='male')x+=-4.8+mi;return clamp(x,0,48)}
function safety(age){const A=[65,75,85],U=[2.1,2.4,3.2],T=[2.9,3.6,5.5],a=clamp(age,65,85);let i=a<=75?0:1,f=(a-A[i])/(A[i+1]-A[i]);return{uka:U[i]+f*(U[i+1]-U[i]),tkr:T[i]+f*(T[i+1]-T[i]),label:age<65?'≤65 reference':age>85?'≥85 reference':'age-adjusted'}}
function lifetime(age){if(age<55)return{u:'~30–40%',t:'~15–22%',n:'Young-patient registry range; lifetime risk is highly age-sensitive.'};if(age<65)return{u:'~15–25%',t:'~7–12%',n:'Literature range across registry and specialist-practice estimates.'};if(age<75)return{u:'~11–14%',t:'~3–5%',n:'Around age 65–69, published NJR modelling reports ~13.7% unicondylar vs ~3.6% unconstrained TKA.'};if(age<85)return{u:'~5–8%',t:'~2–3%',n:'Competing mortality reduces remaining-lifetime revision exposure.'};return{u:'~3–4%',t:'~1–2%',n:'Oldest-age registry context; competing mortality dominates.'}}
function phenotype(){const bad=[],unc=[],non=[];if(state.lateral==='no')bad.push('moderate/severe lateral joint-space loss');else if(state.lateral==='uncertain')unc.push('lateral compartment uncertain');if(state.mcl==='no')bad.push('fixed deformity / MCL incompetence');else if(state.mcl==='uncertain')unc.push('correctability uncertain');if(state.pfj==='yes')bad.push('severe lateral PFJ bone loss/grooving');else if(state.pfj==='uncertain')unc.push('lateral PFJ uncertain');if(state.inflammatory==='yes')bad.push('inflammatory arthropathy');if(state.medialBob==='no')non.push('no definite medial bone-on-bone OA');else if(state.medialBob==='uncertain')unc.push('medial disease severity uncertain');if(state.acl==='no')non.push('ACL deficiency / expanded indication');else if(state.acl==='uncertain')unc.push('ACL competence uncertain');if(+$('ffd').value>=10)non.push('flexion contracture ≥10°');if(+$('flexion').value<110)non.push('maximum flexion <110°');return bad.length?{c:'against',t:'Evidence against standard medial UKA',items:bad}:unc.length?{c:'uncertain',t:'Key information remains uncertain',items:unc}:non.length?{c:'nonstandard',t:'Non-standard / expanded indication',items:non}:{c:'standard',t:'Standard medial UKA phenotype',items:[]}}
function metric(label,val,sub=''){return`<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${val}</div><div class="metric-sub">${sub}</div></div>`}
function evidence(text,pmid){return`<details class="evidence"><summary>Evidence & limitations</summary><div>${text}<br><a target="_blank" rel="noopener" href="https://pubmed.ncbi.nlm.nih.gov/${pmid}/">PubMed ${pmid}</a></div></details>`}
function tradeRow(name,sub,dir,label){return`<div class="trade-row"><div><div class="trade-name">${name}</div><div class="trade-sub">${sub}</div></div><div class="scale"><span class="marker ${dir}"></span></div><span class="badge ${dir==='tkr'?'tkr':dir==='similar'?'similar':'uka'}">${label}</span></div>`}
function render(){['ffd','flexion','age','bmi','oks','volume','usage'].forEach(id=>{const v=$(id).value;$(id+'Out').textContent=id==='ffd'||id==='flexion'?`${v}°`:id==='age'?`${v} years`:id==='bmi'?Number(v).toFixed(1):id==='oks'?`${v} / 48`:id==='usage'?`${v}%`:v});
 const p=phenotype();$('eligibilityCard').className=`card eligibility-card ${p.c}`;$('eligibilityCard').innerHTML=`<div class="eyebrow dark">Stage 1 phenotype</div><div class="eligibility-title">${p.t}</div><div class="microcopy">${p.items.length?'Key flags: '+p.items.join('; '):'Entered anatomy matches the classical evidence-supported medial UKA phenotype.'}</div>`;
 const age=+$('age').value,bmi=+$('bmi').value,pre=+$('oks').value,ffd=+$('ffd').value,band=ageBand(age),construct=$('construct').value;const r=revision[band][state.sex],uRev=r[construct],tRev=r.tkr,s=safety(age),life=lifetime(age),uO=ukaOks(age,pre),tO=tkrOks(age,state.sex,bmi,+state.asa,pre,ffd,state.acl);
 $('tradeoffRows').innerHTML=[tradeRow('Pain & function','Conventional OKS','similar','Broadly similar'),tradeRow('Natural-feeling knee','Forgotten Joint Score','uka','Favours UKA'),tradeRow('10-year revision',`${uRev.toFixed(1)}% vs ${tRev.toFixed(1)}%`,'tkr','Favours TKR'),tradeRow('Lifetime revision','Competing-risk literature','tkr','Favours TKR'),tradeRow('30-day medical safety',`${s.uka.toFixed(1)}% vs ${s.tkr.toFixed(1)}%`,'uka','Favours UKA'),tradeRow('Recovery speed','Early recovery','uka','Favours UKA'),tradeRow('Return to activity','Activity','uka','Favours UKA'),tradeRow('ROM / movement quality','~+5.5° ROM at 2 years','uka','Favours UKA')].join('');
 const provider=+$('volume').value>=30&&+$('usage').value>=20?'Higher-volume / higher-usage UKA context.':+$('volume').value<10||+$('usage').value<10?'Low UKA volume/usage: interpret registry UKA revision estimates cautiously.':'Intermediate provider UKA context.';
 $('outcomesGrid').innerHTML=`
 <article class="outcome-card"><div class="eyebrow dark">PROMs</div><h3>Oxford Knee Score</h3><div class="compare">${metric('UKA ~6 months',uO.toFixed(1),`change ~${(uO-pre>=0?'+':'')+(uO-pre).toFixed(1)}`)}${metric('TKR 12 months',tO.toFixed(1),`change ~${(tO-pre>=0?'+':'')+(tO-pre).toFixed(1)}`)}</div><div class="outcome-copy">These are prognostic research references from different source models/timepoints, not a causal head-to-head prediction. Randomized comparative evidence suggests the conventional OKS difference is small.</div>${evidence('Recent blinded randomized evidence found a modest OKS advantage for UKA that remained below the usual MCID; TOPKAT showed no clinically important mean difference at 10 years.',41662451)}</article>
 <article class="outcome-card"><div class="eyebrow dark">Joint awareness</div><h3>Forgotten Joint Score</h3><div class="outcome-main">Favours UKA</div><div class="delta">Typical comparative difference: about +6 to +14 FJS points with UKA.</div><div class="outcome-copy">Useful comparative evidence, but not an individualized FJS forecast from these sliders.</div>${evidence('Updated comparative evidence consistently shows lower joint awareness after UKA; effect size varies by follow-up.',41825825)}</article>
 <article class="outcome-card"><div class="eyebrow dark">Longevity</div><h3>10-year revision</h3><div class="compare">${metric('UKA',uRev.toFixed(1)+'%',`${band}, ${state.sex}`)}${metric('TKR',tRev.toFixed(1)+'%','cemented unconstrained fixed-bearing')}</div><div class="delta">Absolute excess revision with UKA: +${(uRev-tRev).toFixed(1)} percentage points.</div><div class="outcome-copy">${provider} These are NJR registry strata, not a causal treatment effect.</div>${evidence('Age, sex and UKA construct materially change observed revision. RCT/expert settings can show a smaller gap than registry practice.',41270774)}</article>
 <article class="outcome-card"><div class="eyebrow dark">Longevity</div><h3>Remaining-lifetime revision</h3><div class="compare">${metric('UKA',life.u,'literature range')}${metric('TKR',life.t,'literature range')}</div><div class="outcome-copy">${life.n}</div>${evidence('Age dominates remaining-lifetime revision exposure. Sex and ASA also modify risk, but no complete open equation was identified for faithful individual calculation.',35638212)}</article>
 <article class="outcome-card"><div class="eyebrow dark">Safety</div><h3>30-day morbidity / mortality</h3><div class="compare">${metric('UKA',s.uka.toFixed(1)+'%',s.label)}${metric('TKR',s.tkr.toFixed(1)+'%',s.label)}</div><div class="delta">Approx. ${(s.tkr-s.uka).toFixed(1)} percentage points lower with UKA.</div><div class="outcome-copy">Age-based published anchors; not a full individualized perioperative-risk model.</div>${evidence('Large matched data report lower early morbidity/mortality after UKA with published age-specific probabilities.',39233099)}</article>
 <article class="outcome-card"><div class="eyebrow dark">Recovery & movement</div><h3>Recovery, activity & ROM</h3><div class="outcome-main">Favours UKA</div><div class="delta">Randomized evidence: ~+5.5° greater ROM at 2 years.</div><div class="outcome-copy">UKA also tends to have shorter hospital stay, quicker early recovery and more physiological movement. Return-to-activity evidence generally favours UKA, but individual timing cannot be predicted reliably here.</div>${evidence('Blinded multicentre RCT supports the ROM advantage; broader comparative studies support recovery and movement trends.',41662451)}</article>`;
 const notes=[];notes.push(age<60?'Younger age substantially increases the importance of lifetime revision exposure.':age>=75?'Older age reduces remaining-lifetime revision exposure through competing mortality.':'Age remains an important revision and safety modifier.');if(bmi>=35)notes.push('Higher BMI affects some TKR prognostic models, but is not treated as an anatomical UKA exclusion.');if(+state.asa>=3)notes.push('Higher ASA increases absolute medical-risk context; it is not allowed to drive unrelated outcome domains.');notes.push(provider);if(p.c!=='standard')notes.push('Stage 1 anatomy is not fully standard, so Stage 2 numbers should not override the anatomical assessment.');$('scenarioNotes').innerHTML=notes.map(n=>`<div class="note">${n}</div>`).join('');
}
document.querySelectorAll('.segmented').forEach(group=>group.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;group.querySelectorAll('button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');state[group.dataset.input]=e.target.dataset.value;render()}));
['ffd','flexion','age','bmi','oks','volume','usage','pain','construct'].forEach(id=>$(id).addEventListener('input',render));
const presets={younger:{age:52,bmi:27,oks:18,ffd:0,flexion:125,volume:35,usage:25,sex:'male',asa:'1'},typical:{age:65,bmi:28,oks:20,ffd:0,flexion:120,volume:30,usage:20,sex:'female',asa:'2'},older:{age:80,bmi:29,oks:19,ffd:5,flexion:115,volume:30,usage:20,sex:'female',asa:'3'}};
function applyPreset(x){const p=presets[x];Object.entries(p).forEach(([k,v])=>{if($(k))$(k).value=v;else state[k]=String(v)});document.querySelectorAll('.segmented').forEach(g=>g.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.value===state[g.dataset.input])));render()}
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));$('resetAll').addEventListener('click',()=>applyPreset('typical'));render();